### PR TITLE
 renamed chart name and file names

### PR DESCRIPTION
**Pull request by xrajesh**
We renamed the insights charts to reflect the larger use of policyreport from the GRC squad . From discussion with @bjoydeep 
@zkayyali812 @nathanweatherly - Please let me know if anything needs to be changed from install side.
@SherinV We have to update the threatmodel doc I think :( 

/hold
`/hold`

### CODE REVIEW

**Comment by zkayyali812** [comment]
From the installer side, we will need to update our automation to capture the rename changes.

@xrajesh Is the name of this repository changing from `insights-chart` to `policyreport` as well?

I created PR - https://github.com/open-cluster-management/multiclusterhub-repo/pull/429 to capture our MCH repo automation update since the rename will affect our automation

**Comment by xrajesh** [comment]
I am not planning to change the repo name @zkayyali812

**Review by jlpadilla — APPROVED** [review]
/lgtm

**Comment by nathanweatherly** [comment]
@xrajesh I will discuss with team-- sorry didn't see request for review earlier. Please don't merge until you hear from us- I think this will require installer changes.

Also, @xrajesh can you remind me-- was insights installed as part of ACM 2.2?

**Review by zkayyali812 — APPROVED** [review]

**Pull request merged**
